version: "3.8"

services:
  docker:
    image: docker:26-dind
    container_name: jenkins-dind
    privileged: true
    user: root
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker_data:/var/lib/docker
      - docker_certs:/certs
      - jenkins_home:/var/jenkins_home
    networks:
      jenkins-net:
        aliases:
          - docker

  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs:/certs:ro
    networks:
      - jenkins-net
    restart: unless-stopped

volumes:
  docker_data:
  docker_certs:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
