version: '3.8'

services:
  # Docker-in-Docker service
  dind:
    image: docker:dind
    container_name: jenkins-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-storage:/var/lib/docker
      - dind-certs:/certs
    networks:
      - jenkins-network
    restart: unless-stopped
    command: 
      - --storage-driver=overlay2
      - --tls=false

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - DOCKER_TLS_VERIFY=0
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Alternative approach
    networks:
      - jenkins-network
    depends_on:
      - dind
    restart: unless-stopped
    privileged: true

volumes:
  jenkins_home:
    name: jenkins-home-data
  dind-storage:
    name: dind-storage-data
  dind-certs:
    name: dind-certs-data

networks:
  jenkins-network:
    name: jenkins-network
    driver: bridge
